sudo: required
services:
  - xvfb
language: node_js
node_js:
  - 6

script: ./node_modules/.bin/run-tests

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true

env:
  matrix:
    - BROWSER=chrome  BVER=stable
    - BROWSER=firefox BVER=stable
    - UNIT_CMD='npm run lint'
  global:
    - TRAVIS=true
    - UNIT_CMD='npm run unit'

matrix:
  fast_finish: true

notifications:
  email:
    - manik@tokbox.com
